name: AI Direct Commit (paste a diff)
on:
  workflow_dispatch:
    inputs:
      patch:
        description: "Unified diff, but on ONE line with \\n escapes"
        required: true
      message:
        description: "Commit message (one line)"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Rehydrate diff to file (preserve newlines)
        shell: bash
        run: |
          set -euo pipefail
          python - <<'PY'
import json
s = json.loads(r'''${{ toJSON(inputs.patch) }}''')   # one line from UI
# Turn literal escape sequences into real newlines/tabs
s = s.replace('\\r\\n','\n').replace('\\n','\n').replace('\\t','\t')
open('/tmp/patch.diff','w',encoding='utf-8').write(s)
print("Wrote /tmp/patch.diff with", len(s.splitlines()), "lines")
PY
          echo "---- preview ----"
          head -n 20 /tmp/patch.diff || true

      - name: Apply patch, commit, push (as you)
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git apply --whitespace=fix --index /tmp/patch.diff
          git diff --cached --quiet && { echo "No changes to commit"; exit 0; }
          git commit -m "${{ inputs.message }}"
          git remote set-url origin "https://x-access-token:${MY_PAT}@github.com/${{ github.repository }}.git"
          git push origin HEAD:main
