name: AI Direct Commit (paste a base64 diff)
on:
  workflow_dispatch:
    inputs:
      patch_b64:
        description: "Unified diff, base64-encoded"
        required: true
      message:
        description: "Commit message"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Decode diff
        run: |
          set -euo pipefail
          echo "${{ inputs.patch_b64 }}" | base64 -d > /tmp/patch.diff
          echo "==== preview ===="
          head -n 20 /tmp/patch.diff || true

      - name: Apply patch, commit, push (as you)
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          set -euo pipefail
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git apply --whitespace=fix --index /tmp/patch.diff
          git diff --cached --quiet && { echo 'No changes'; exit 0; }
          git commit -m "${{ inputs.message }}"
          git remote set-url origin "https://x-access-token:${MY_PAT}@github.com/${{ github.repository }}.git"
          git push origin HEAD:main
