name: AI Direct Commit (paste a diff)
on:
  workflow_dispatch:
    inputs:
      patch:
        description: "Paste a unified diff (human-readable)"
        required: true
      message:
        description: "Commit message (short, one line)"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: {}  # we'll push with your PAT, not GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Write pasted diff to file
        shell: bash
        run: |
          # Write raw input (can include newlines) into a file
          cat > /tmp/patch.diff <<'PATCH_EOF'
${{ inputs.patch }}
PATCH_EOF

          # quick sanity check: looks like a git-style patch?
          head -n 1 /tmp/patch.diff | grep -Eq '^(---|diff --git)' || {
            echo "Input doesn't look like a unified diff"; exit 1; }

      - name: Apply patch, commit, push (as you)
        env:
          MY_PAT: ${{ secrets.MY_PAT }}   # your fine-grained PAT
        shell: bash
        run: |
          set -euo pipefail

          # Configure author/committer identity (YOU)
          git config user.name  "YOUR NAME HERE"
          git config user.email "yourname@users.noreply.github.com"
          # (Use your verified noreply or verified email)

          # Apply and stage changes
          git apply --whitespace=fix --index /tmp/patch.diff || {
            echo "git apply failed"; exit 1; }

          # If nothing changed, stop quietly
          git diff --cached --quiet && { echo "No changes to commit"; exit 0; }

          # Commit with the message you entered
          git commit -m "${{ inputs.message }}"

          # Push to main using your PAT (so it shows as you, not actions[bot])
          git remote set-url origin \
            https://x-access-token:${MY_PAT}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
