name: AI Direct Commit (paste a diff)
on:
  workflow_dispatch:
    inputs:
      patch:
        description: "Paste a unified diff (human-readable)"
        required: true
      message:
        description: "Commit message (short, one line)"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write pasted diff to file
        shell: bash
        run: |
          set -euo pipefail
          # Write raw multi-line input to a file
          echo "${{ inputs.patch }}" | sed 's/\\n/\n/g' > /tmp/patch.diff

          # quick sanity check: looks like a git-style patch?
          head -n 1 /tmp/patch.diff | grep -Eq '^(---|diff --git)' || {
            echo "Input doesn't look like a unified diff"; exit 1; }

      - name: Apply patch, commit, push (as you)
        env:
          MY_PAT: ${{ secrets.MY_PAT }}   # your fine-grained PAT
        shell: bash
        run: |
          set -euo pipefail

          # Use your identity automatically
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          # Apply and stage changes
          git apply --whitespace=fix --index /tmp/patch.diff

          # If nothing changed, stop quietly
          git diff --cached --quiet && { echo "No changes to commit"; exit 0; }

          # Commit with the provided message
          git commit -m "${{ inputs.message }}"

          # Push to main using your PAT (so it shows as you)
          git remote set-url origin \
            "https://x-access-token:${MY_PAT}@github.com/${{ github.repository }}.git"
          git push origin HEAD:main
